# Generated by Django 2.2.6 on 2026-01-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20230830_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='full_path',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
