# Generated by Django manual

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20260111_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='error_msg',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
