# Generated by Django manual

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_task_error_msg_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrecord',
            name='error_msg',
            field=models.TextField(default=''),
        ),
    ]
